### PR TITLE
blacklist, implemented with role and not fucking retarded

### PR DESCRIPTION
**Pull request by RandomContributor**
dont you fucking dare not merge

### CODE REVIEW

**Comment by RandomContributor** [comment]
fixes #68 #98

**Comment by RandomContributor** [comment]
@ZeroMemes I still have to implement randomweeb

**Comment by RandomContributor** [comment]
so please

**Comment by ZeroMemes** [comment]
pog gers

**Comment by RandomContributor** [comment]
<3

**Pull request merged**
