### PR TITLE
typos

### PR DESCRIPTION
**Pull request by ehylo**
imagine not being able to type impact correctly

### CODE REVIEW

**Comment by CesiumCs** [comment]
did you think about if that was on purpose

**Comment by ehylo** [comment]
> did you think about if that was on purpose

if it was on purpose it kinda makes no sense, I could understand just the stupid but why the other place

**Comment by LeafHacker** [comment]
Pretty sure those _are_ deliberate typos but I'm not against merging this. @leijurv?

**Comment by leijurv** [comment]
Yeah these are intentional for the funny

**Pull request closed without merging**
