### PR TITLE
Update replies.js

### PR DESCRIPTION
**Pull request by ghost**
you can do macros in game now since however long

### CODE REVIEW

**Comment by SuperOP535** [comment]
I think it is better to just remove the reply then

**Comment by ghost** [comment]
But people still ask about macros, suggesting they don't know its there

**Comment by SuperOP535** [comment]
Then we should remove the issue URL as it would possibly mislead a tiny percent of people. (in impact community this percent isn't actually tiny)

**Comment by ghost** [comment]
I agree, edit it :)

**Pull request merged**
