### PR TITLE
make bot reply to "good bot"

### PR DESCRIPTION
**Pull request by skylykat**
sorry if regex is dumb i dont know how to do regex

### CODE REVIEW

**Comment by skylykat** [comment]
yes very good please merge this i love skylykat's idea

**Review by berrely — CHANGES_REQUESTED** [review]
Maybe bump this down to -1?

**Comment by skylykat** [comment]
epic

**Comment by CesiumCs** [comment]
> Maybe bump this down to -1?

what do you expect to happen when you make it -1

**Comment by skylykat** [comment]
make it 596523.235

**Pull request merged**
