### PR TITLE
chess

### PR DESCRIPTION
**Pull request by thaqalayn**
this probably works idk

### CODE REVIEW

**Comment by thaqalayn** [comment]
@zPeanut

**Comment by thaqalayn** [comment]
@leijurv i wuv weijurv pwease weview my pr

**Comment by thaqalayn** [comment]
p(rawr)

**Review by leijurv — CHANGES_REQUESTED** [review]
unrelated free pepsi change should be its own PR

**Comment by CesiumCs** [comment]
commit messages tell a hilarious story sometimes

**Pull request merged**
