### PR TITLE
ungiveaway, fuck you

### PR DESCRIPTION
**Pull request by RandomContributor**

### CODE REVIEW

**Comment by 0-x-2-2** [comment]
nyo!

**Comment by ghost** [comment]
not happening

**Comment by RandomContributor** [comment]
> nyo!

now me is sad, pls

**Comment by RandomContributor** [comment]
Aw fuck me.

**Comment by bddvlpr** [comment]
not happening

**Review by bddvlpr — CHANGES_REQUESTED** [review]
Delete these lol

**Comment by ghost** [comment]
image

**Comment by RandomContributor** [comment]
> Delete these lol

No.

**Comment by bddvlpr** [comment]
image

**Review by Grass0001 — APPROVED** [review]

**Review by SoNothingMC — APPROVED** [review]

**Pull request merged**
