### PR TITLE
make bot wespnyond wwith a cuwtew messagye

### PR DESCRIPTION
**Pull request by skylykat**
rawr x3

### CODE REVIEW

**Comment by DoctorBang** [comment]
No, stop it.

**Comment by skylykat** [comment]
no uwu

**Review by CesiumCs — APPROVED** [review]
very valuable addition to the bot! please merge!

**Comment by skylykat** [comment]
very valuable addition to the bot! please merge!

**Comment by skylykat** [comment]
very valuable addition to the bot! please merge!

**Comment by Fakeaccount12312** [comment]
make it respond to `good bot uwu`

**Comment by zPeanut** [comment]
no

**Comment by skylykat** [comment]
pls

**Comment by skylykat** [comment]
it is a great addition to the bot
pls merge

**Comment by hamzaayadeh** [comment]
UwU

**Pull request merged**
